[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
build_src_filter = +<main_wifi.cpp>

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    4-20ma/ModbusMaster@^2.0.1

upload_speed = 921600